version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  executor:
    build:
      context: ./src/executor
      dockerfile: Dockerfile.exec
    image: executor
    container_name: executor

  celery-worker:
    build:
      context: .
    container_name: celery-worker
    command: celery -A src.tasks worker --loglevel=info
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
      - executor

  streamlit:
    build:
      context: .
    container_name: streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
      - executor
