version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  celery-worker:
    build:
      context: ./backend/judge
    container_name: celery-worker
    command: celery -A src.tasks worker --loglevel=info
    volumes:
      - ./judge:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - app_data:/app/data
    depends_on:
      - redis
    
  flower:
    build: 
      context: ./backend/judge
    image: mher/flower
    container_name: flower
    command: ["celery", "-A", "src.tasks", "flower", "--port=5555", "--broker=redis://redis:6379/0"]
    ports:
      - "5555:5555"
    depends_on:
      - redis

  backend:
    build:
      context: ./backend/app
    container_name: backend 
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - app_data:/app/data
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  app_data: