version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.celery
    container_name: celery-worker
    command: celery -A judge.tasks worker --loglevel=info
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/app/data
    depends_on:
      - redis
    
  flower:
    build:
      context: ./backend
      dockerfile: Dockerfile.celery
    image: mher/flower
    container_name: flower
    command: celery -A judge.tasks --broker=redis://redis:6379/0 flower --port=5555 
    ports:
      - "5555:5555"
    depends_on:
      - redis

  backend:
    build:
      context: ./backend
    container_name: backend 
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/app/data
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  data: