FROM python:3.11-slim

RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN pip install numpy torch scikit-learn

WORKDIR /app

COPY src/ /app/

CMD ["tail", "-f", "/dev/null"]

